### ISSUE TITLE
Option to skip PR title changes

### ISSUE THREAD

**Issue by houserx-jmcc** [microsoft/PR-Metrics#422]
## Summary

An input option to *not* alter a pull request's title would be really helpful. 

## Rationale

In the scenario where you are squashing merge commits, the additional prefix on the pull request makes it difficult to apply standard semver parsing to get versioning for a set of commits. I've encountered difficult with this when using GitHub Actions (https://github.com/ietf-tools/semver-action) as well as trying to create regex for GitHub branch rulesets. Making this feature something that can be toggled should be relatively easy.

**Comment by muiriswoulfe** [comment]
Hi @houserx-jmcc, thanks for using PR Metrics and for your input on this.

I understand the rationale behind your request, but unfortunately, we don't have the capacity to take this on at the current time. If you wish to work on this, I would be happy to support you.

Alternatively, we can look to add this at a later stage, although I doubt there will be capacity to deal with this before year-end.

**Comment by houserx-jmcc** [comment]
Thanks for the response! If I can find time I will make a PR for it.

**Comment by houserx-jmcc** [comment]
Planning on trying to get something up on this for Hacktoberfest 🚀

**Comment by muiriswoulfe** [comment]
Closing this issue as there hasn't been progress on this in some time. I'm still happy to support this being added, so we can reopen this if necessary.
