### ISSUE TITLE
file-matching-patterns only respects first match pattern

### ISSUE THREAD

**Issue by twalshOG** [microsoft/PR-Metrics#431]
## Summary
File/folder matching only respects the first match provided, subsequent matches are ignored

## Reproduction Steps

Create a project with with 3 sibling folders
Add a test file (like a simple typescript file) to all 3 folders
So it will look like this:
- Root
  - src
    - file.ts 
  - \_\_test\_\_
    - file.test.ts
  - Other
    - Other.ts
  
Create a pipeline to run the github action
```
          file-matching-patterns: | 
            src/*.ts  
            __test__/*.ts 
``` 
  
Run the pipeline with the actions. 

Notes

1. Logs with indicate `Setting the file matching patterns input to '["src/*.ts","__test__/*.ts"]`
2. Folder2 content is excluded

## Additional Information

Work around is to use this syntax: 
`file-matching-patterns: {src/**/*.ts ,__test__/**/*.ts}`

**Comment by muiriswoulfe** [comment]
Thanks @twalshOG for using PR Metrics and for reporting the issue. I've now got PR #432 out for the issue, which also simplifies what was very complex logic and therefore was quite error prone.

**Comment by muiriswoulfe** [comment]
@twalshOG: The latest release of PR Metrics, v1.5.9, which is now available in the store for both GitHub and Azure DevOps includes the fix.
