### ISSUE TITLE
Workflow completes with success despite expired token

### ISSUE THREAD

**Issue by philcart** [microsoft/PR-Metrics#459]
## Summary

The workflow action runs and completes successfully despite having an expired token. The error message is visible in the log for the workflow.

## Reproduction Steps

Create a workflow action using a valid token and run it successfully.
Expire the token.
Re-run the workflow.

## Additional Information

**UI list of "successful" runs**
![image](https://github.com/microsoft/PR-Metrics/assets/4084083/cf459b6e-0cb9-49da-ba96-fd7d3406bd96)

**UI Details from run #3444**
![image](https://github.com/microsoft/PR-Metrics/assets/4084083/19fe91c3-4f6a-4b34-93ad-649eae9208a6)

**Error Messages from log**
```
HttpError – stack: "HttpError: Could not access the resources. Ensure the 'PR_Metrics_Access_Token' secret environment variable 
has access to 'repos' (or Read and Write access to pull requests if using a Fine-Grained PAT).\n    
    at /home/runner/work/_actions/microsoft/PR-Metrics/v1.5.2/dist/index.js:1:197755\n    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    
    at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/microsoft/PR-Metrics/v1.5.2/dist/index.js:1:189586)\n    
    at async Job.doExecute (/home/runner/work/_actions/microsoft/PR-Metrics/v1.5.2/dist/index.js:1:1157[36]
    (https://github.com/SchiavelloIT/Schiavello.Cyberdyne/actions/runs/7795962582/job/21259779652#step:3:37)0)"
HttpError – message: "Could not access the resources. Ensure the 'PR_Metrics_Access_Token' secret environment variable 
has access to 'repos' (or Read and Write access to pull requests if using a Fine-Grained PAT)."
HttpError – name: "HttpError"
HttpError – status: 401
HttpError – response: {"url":"https://api.github.com/repos/SchiavelloIT/Schiavello.Cyberdyne/pulls/1245",
    "status":401,"headers":{"access-control-allow-origin":"*",
    "access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, 
        X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, 
        X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
    "connection":"close","content-length":"80","content-security-policy":"default-src 'none'",
    "content-type":"application/json; charset=utf-8","date":"Tue, 06 Feb 2024 07:10:12 GMT",
    "referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin",
    "server":"GitHub.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload",
    "vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-frame-options":"deny",
    "x-github-media-type":"github.v3; format=json","x-github-request-id":"C[38]
    (https://github.com/SchiavelloIT/Schiavello.Cyberdyne/actions/runs/7795962582/job/21259779652#step:3:39)1:6F1B:CFB47A:1A4A76B:65C1DB54","x-ratelimit-limit":"60","x-ratelimit-remaining":"58",
    "x-ratelimit-reset":"1707205134","x-ratelimit-resource":"core","x-ratelimit-used":"2","x-xss-protection":"0"},
    "data":{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}}
```

**Comment by muiriswoulfe** [comment]
Hi @philcart, thanks for using PR Metrics and for taking the time to submit this issue.

I've tried out your repro locally, but I don't see the issue. When I expire the token, the job fails for me.

I see that, in your case, the error is being logged but the job is returning its status as successful. I would expect this to be the case if `continue-on-error` were defined for that job (or at a higher level of the workflow that covers the job).

`continue-on-error` is recommended in the README as it wouldn't be best practice to fail your entire build if PR Metrics fails. It will, however, result in issues like the one you identified being missed so you need to decide what is best for your case. I'd also recommend scoping `continue-on-error` to just the PR Metrics job as you wouldn't want to continue if key elements of the build failed, but again this will depend on your specific setup.

If you don't have `continue-on-error` set or changing this doesn't resolve the issue, could you provide your workflow definition for further investigation? You can remove unrelated jobs but I'd appreciate if you could leave in the `job` definitions as settings at the job level can impact the constituent tasks.

**Comment by muiriswoulfe** [comment]
Closing this issue as there hasn't been a response in over a week. Feel free to reopen if there is an update.
