### ISSUE TITLE
PR validation time

### ISSUE THREAD

**Issue by cedrox** [microsoft/PR-Metrics#479]
## Summary
We want to add metric about duration between published (not draft) and completed. This can be interesting to have the metric of how long the pull request is lasting directly on the PR but it should also be great to have it in Analytics view. **Do you know an easy way to have the PR duration from the publication (not draft) to the completion ?**
Also I know that we have the file count but can we have also the team count ?
is it possible to have this metrics for an overall Repo in a central place ?
Another metric could be interesting: the Count of published (how many time from draft to publish back to draft...)

## Rationale

It's heart metric of a PR and will help to do proper PR

## Additional Information

It would be great to have it directly in the tool without to build intermediate tool like CCOInsights report [ADO Dashboard Deployment Guide · Azure/CCOInsights Wiki · GitHub](https://github.com/Azure/CCOInsights/wiki/ADO%20Dashboard%20-%20Deployment%20Guide)

**Comment by muiriswoulfe** [comment]
Hi @cedrox,

Thanks for using PR Metrics and for submitting feedback.

Unfortunately, your suggestion is out of scope for PR Metrics, which is designed to be a lightweight solution that runs as part of the build loop.

To address your needs, I'd suggest looking into the Azure DevOps or GitHub APIs. You should be able to compute the metrics for which you're looking. You could run these locally as a PowerShell or Python script if you don't want to go to the effort of creating an extension.

**Comment by cedrox** [comment]
Hello @muiriswoulfe  and thanks for your feedback. That's perfectly clear. There is some beginning of answer available on this repo: https://github.com/Azure/CCOInsights
