### ISSUE TITLE
Checkout action requirement is missing from the docs

### ISSUE THREAD

**Issue by dstrants** [microsoft/PR-Metrics#542]
## Summary
We started using the action and after a couple of failures that the checkout action is required with `fetch-depth: 0` in order for the action properly operate.

I checked the readme again and could not find any reference to that although it is a prerequisite.
I'd be happy to add the missing information myself but I am not sure where would be the right place to do so in the readme. Probably a full action example would be most helpful

**Comment by muiriswoulfe** [comment]
Hi @dstrants, thanks for your feedback and your offer to make the update.

The details about this are nuanced, and not every repo will require this to be added. The advice is only to include it if the task returns this as a specific error message.

I've now included details around this in the docs as suggested.
